# Author: Carsten Gips <carsten.gips@fh-bielefeld.de>
# Copyright: (c) 2016-2018 Carsten Gips
# License: MIT



## Path to the Pandoc-Lecture git sub-module

DATADIR = ..



## Uncomment to use a local binary (or define environment variable)
## If PANDOC is unset a docker image will be used

#PANDOC = pandoc-2.2.3



## Source files and lecture prefix

SRC = $(wildcard b*.md)
ID  = pm



## Include Pandoc-Lecture Makefile for definitions

include $(DATADIR)/make/homework.mk




